/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;

import dao.BangLuongNhanVienDAO;
import entity.BangLuongNhanVien;
import tablemodels.InBangLuongNhanVienTableModel;

/**
 *
 * @author Hoang Truong
 */
public class BangLuongNhanVienIn extends javax.swing.JPanel {

	private static final String[] HEADERS = { "Mã bảng lương", "Mã nhân viên", "Họ tên", "Tổng lương", "Xác nhận" };

	private InBangLuongNhanVienTableModel inBangLuongNhanVienTableModel;
	private List<BangLuongNhanVienIn> dsbl;
	private BangLuongNhanVienIn bangLuongNhanVien;
	private BangLuongNhanVienDAO bangLuongNhanVienDAO;
	private List<String> tongLuong;
	private int thangTinhLuong;
	private int namTinhLuong;

	public BangLuongNhanVienIn(int thangTinhLuong, int namTinhLuong, List<String> tongLuong) {
		this.tongLuong = tongLuong;
		this.thangTinhLuong = thangTinhLuong;
		this.namTinhLuong = namTinhLuong;
		tblInBangLuong = new JTable();
		dsbl = new ArrayList<>();
		bangLuongNhanVienDAO = new BangLuongNhanVienDAO();
		initComponents();
		themSuKien();
	}



	private void updateModelTable( String[] headers, List<entity.BangLuongNhanVien> dsbl, List<String> tongLuong) {
		inBangLuongNhanVienTableModel = new InBangLuongNhanVienTableModel(headers, dsbl, tongLuong);
		tblInBangLuong.setModel(inBangLuongNhanVienTableModel);
		tblInBangLuong.updateUI();
	}

	private void themSuKien() {
		List<BangLuongNhanVien> danhSachBangLuongNhanVien = null;
		try {
			danhSachBangLuongNhanVien = bangLuongNhanVienDAO.layDanhSachTinhLuong(thangTinhLuong, namTinhLuong);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		if(danhSachBangLuongNhanVien.size() == 0)
			 lblTieuDe.setText("BẢNG LƯƠNG NHÂN VIÊN");
		else  lblTieuDe.setText("BẢNG LƯƠNG NHÂN VIÊN  " + danhSachBangLuongNhanVien.get(0).getNgayTinhLuong());
		
		updateModelTable(HEADERS, danhSachBangLuongNhanVien, tongLuong);

		
		
		btnInBangLuong.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {

				Date ngayIn = new java.sql.Date(new java.util.Date().getTime());
				SimpleDateFormat dt = new SimpleDateFormat("dd-MM-yyyy");
				String formatDate = dt.format(ngayIn);



				MessageFormat header = new MessageFormat("BẢNG LƯƠNG NHÂN VIÊN  " + formatDate  );
				MessageFormat footer = new MessageFormat("Quản lí lương sản phẩm - Nhóm 4");


				
				
				try {
					if(tblInBangLuong.print(JTable.PrintMode.FIT_WIDTH, header, footer))
						JOptionPane.showMessageDialog(null, "In thành công");
				} catch (Exception e2) {
					JOptionPane.showMessageDialog(null, "In thất bại" + e2.getMessage());
				}

			}

		});

		btnHuy.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnHuyActionPerformed(evt);
			}

			private void btnHuyActionPerformed(ActionEvent evt) {
				Window window = SwingUtilities.getWindowAncestor(btnHuy);
				window.dispose();

			}
		});
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInBangLuong = new javax.swing.JPanel();
        btnInBangLuong = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        lblTieuDe = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblInBangLuong = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        pnlInBangLuong.setBackground(new java.awt.Color(255, 255, 255));

        btnInBangLuong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnInBangLuong.setText("Xác nhận in");
        btnInBangLuong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnHuy.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close.png"))); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTieuDe.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
       

        tblInBangLuong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblInBangLuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", "", null},
                {"", "", "", "", null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Mã lương", "Họ và tên ", "Tổng lương", "Xác nhận"
            }
        ));
        tblInBangLuong.setEnabled(false);
        tblInBangLuong.setFocusable(false);
        tblInBangLuong.setRequestFocusEnabled(false);
        jScrollPane9.setViewportView(tblInBangLuong);

        javax.swing.GroupLayout pnlInBangLuongLayout = new javax.swing.GroupLayout(pnlInBangLuong);
        pnlInBangLuong.setLayout(pnlInBangLuongLayout);
        pnlInBangLuongLayout.setHorizontalGroup(
            pnlInBangLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInBangLuongLayout.createSequentialGroup()
                .addContainerGap(475, Short.MAX_VALUE)
                .addComponent(btnInBangLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(313, 313, 313))
            .addGroup(pnlInBangLuongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInBangLuongLayout.setVerticalGroup(
            pnlInBangLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInBangLuongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInBangLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInBangLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        add(pnlInBangLuong, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnInBangLuong;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPanel pnlInBangLuong;
    private javax.swing.JTable tblInBangLuong;
    // End of variables declaration//GEN-END:variables
}
