/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.border.MatteBorder;
import javax.swing.table.TableColumnModel;

import dao.BangChamCongNhanVienDAO;
import entity.BangChamCongNhanVien;
import entity.DiaChi;
import tablemodels.BangChamCongNVTableModel;
import dao.NhanVienDAO;
import tablemodels.NhanVienTableModel;
import entity.NhanVien;
import setting.PathSetting;
public class ChamCongNhanVien extends javax.swing.JPanel {

	/**
	 * Creates new form ChamCongNhanVien
	 */
	private BangChamCongNhanVienDAO chamCongNhanVienDAO;
	private BangChamCongNVTableModel chamCongNVTableModel;
	private List<BangChamCongNhanVien> dsCCNV;
	private NhanVienDAO nhanVienDAO;
	private NhanVienTableModel nhanVienTableModel;
	private List<NhanVien> dsNV;
	private NhanVien nhanVienLogin;
	private Date ngayChamCong;
	private static final String[] HEADERS = { "Mã chấm công", "Mã nhân viên", "Tên nhân viên","Số giờ làm thêm", "Ngày chấm công" , "Tình trạng", "Mã người chấm công", "Tên người chấm công","Tình trạng công"};
	private static final String[] HEADERSNV = { "Mã nhân viên", "Tên nhân viên", "Ngày Sinh", "Email"};
	public ChamCongNhanVien(NhanVien nvLogin) {
		chamCongNhanVienDAO = new BangChamCongNhanVienDAO();
		nhanVienDAO = new NhanVienDAO();
		this.nhanVienLogin = nvLogin;
		initComponents();
		themSuKien();
		setWidthTable();
		btnChamGioVe.setEnabled(false);
		btnChamGioVe.repaint();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void setWidthTable() {
		tblChamCong.getColumnModel().getColumn(0).setMinWidth(10);
		tblChamCong.getColumnModel().getColumn(1).setMinWidth(50);
		tblChamCong.getColumnModel().getColumn(2).setMinWidth(60);
		tblChamCong.getColumnModel().getColumn(3).setMinWidth(20);
		tblChamCong.getColumnModel().getColumn(4).setMinWidth(30);
		tblChamCong.getColumnModel().getColumn(5).setMinWidth(30);
		tblChamCong.getColumnModel().getColumn(6).setMinWidth(50);
		tblChamCong.getColumnModel().getColumn(7).setMinWidth(60);
		tblChamCong.getColumnModel().getColumn(8).setMinWidth(39);


	}
	private void updateChamCongNhanVienModelTable(List<BangChamCongNhanVien> dsCCNV,String[] headers) {
		chamCongNVTableModel = new BangChamCongNVTableModel(dsCCNV, headers);
		tblChamCong.setModel(chamCongNVTableModel);
		setWidthTable();
		tblChamCong.updateUI();

	}

	private void updateNhanVienModelTable(List<NhanVien> dsNV,String[] headersnv) {
		nhanVienTableModel = new NhanVienTableModel(headersnv, dsNV);
		tblNhanVien.setModel(nhanVienTableModel);
		tblNhanVien.updateUI();
	}
	private void fillThongTinChamCongNV(BangChamCongNhanVien chamCongNhanVien) {
		txtMaNhanVien.setText(chamCongNhanVien.getNhanVien().getMaNhanVien());
		txtTenNhanVien1.setText(chamCongNhanVien.getNhanVien().getTenNhanVien());
		//    	txtSoGioLamThemCC.setText(chamCongNhanVien.getNhanVien().getTenNhanVien());
		txtMaNguoiChamCong.setText(chamCongNhanVien.getNguoiChamCong().getMaNhanVien());
		txtTenNguoiChamCong.setText(chamCongNhanVien.getNguoiChamCong().getTenNhanVien());
		cmbTinhTrang.setSelectedItem(chamCongNhanVien.getTrangThai());
		//    	cmbCaLam.setSelectedItem(chamCongNhanVien.getCaLam());
		txtSoGioLamThem.setText(String.format("%.2f", chamCongNhanVien.getSoGioLamThem()));


		dtNgayChamCong.setDate(chamCongNhanVien.getNgayChamCong());
		cmbTinhTrangCong.setSelectedItem(chamCongNhanVien.getTinhTrangChamCong());
		//    	
	}
	private String maChamCongMoi(String maChamCong) {
		String maChamCongMoi = null;
		if(maChamCong == null){
			maChamCongMoi = "CC000001";

		}
		else{
			int number = Integer.parseInt(maChamCong.substring(2));
			number++;
			maChamCongMoi = String.format("CC%06d", number);
			//            System.out.println(maChamCongMoi);
		}

		return maChamCongMoi;
	}
	private void xoaRong() {
		txtMaNhanVien.setText("");
		txtTenNhanVien1.setText("");
		txtMaNguoiChamCong.setText("");
		dtNgayChamCong.setDate(null);
		txtTenNguoiChamCong.setText("");
		txtSoGioLamThem.setText("");


	}
	private void batTextfield() {
		txtMaNhanVien.setEditable(true);
		txtTenNhanVien1.setEditable(true);
		txtSoGioLamThem.setEditable(true);
		txtMaNguoiChamCong.setEditable(true);
		txtTenNguoiChamCong.setEditable(true);
		//    	cmbCaLam.setEnabled(true);
		cmbTinhTrang.setEnabled(true);
		dtNgayChamCong.setEnabled(true);
		cmbTinhTrangCong.setEnabled(true);




	}
	private void tatTextfield() {
		txtMaNhanVien.setEditable(false);
		txtTenNhanVien1.setEditable(false);
		txtSoGioLamThem.setEditable(false);
		txtMaNguoiChamCong.setEditable(false);
		txtTenNguoiChamCong.setEditable(false);
		//    	cmbCaLam.setEnabled(false);
		cmbTinhTrang.setEnabled(false);
		dtNgayChamCong.setEnabled(false);
		cmbTinhTrangCong.setEnabled(false);




	}
	private BangChamCongNhanVien getDuLieuTuTextField() {
		BangChamCongNhanVien chamCongNhanVien = null;
		String maChamCong = (String) tblChamCong.getModel().getValueAt(tblChamCong.getSelectedRow(), 0);
		String maNhanVien = txtMaNhanVien.getText().trim();
		NhanVien nhanVien = nhanVienDAO.timNhanVienBangMaNhanVien(maNhanVien);
		Date ngayChamCong = dtNgayChamCong.getDate();
		String tinhTrang = cmbTinhTrang.getSelectedItem().toString();
		//		String caLam = cmbCaLam.getSelectedItem().toString();
		String tinhTrangChamCong = cmbTinhTrangCong.getSelectedItem().toString();
		double soGioLamThem = Double.parseDouble(txtSoGioLamThem.getText().trim().equalsIgnoreCase("")? "0" : txtSoGioLamThem.getText().trim());
		List<NhanVien> dsNV = nhanVienDAO.layDanhSachNhanVien();
		return chamCongNhanVien = new BangChamCongNhanVien(maChamCong, soGioLamThem, ngayChamCong, tinhTrang, dsNV.get(2), nhanVien,tinhTrangChamCong);
	}
	private BangChamCongNhanVien layDuLieuDeChamCong() {
		if(tblNhanVien.getSelectedRow() != -1) {
			String maNhanVien = (String) tblNhanVien.getModel().getValueAt(tblNhanVien.getSelectedRow(), 0);
			NhanVien nhanVien = nhanVienDAO.timNhanVienBangMaNhanVien(maNhanVien);
			Date ngayChamCong = null;
			try {
				ngayChamCong = dtNgayChamCongCC.getDate();
				if(ngayChamCong == null) {
					JOptionPane.showMessageDialog(null, "Chưa chọn ngày chấm công");
					return null;
				}
			} catch (Exception e) {
				// TODO: handle exception

				e.printStackTrace();
			}
			String tinhTrang = cmbTinhTrangCC.getSelectedItem().toString();
			String tinhTrangCong = "Nửa công";
			return new BangChamCongNhanVien(maChamCongMoi( chamCongNhanVienDAO.layMaChamCongCaoNhat()), 0, ngayChamCong, tinhTrang, nhanVienLogin, nhanVien,tinhTrangCong);
		}
		return null;

	}
	private void danhSachChamCongHomNay() {
		long homNay = dtNgayChamCongCC.getDate().getTime();
		List<BangChamCongNhanVien> dsHomNay = new ArrayList<>();
		dsHomNay = chamCongNhanVienDAO.layDanhSachCCNVHomNay(new java.sql.Date(homNay));
		updateChamCongNhanVienModelTable(dsHomNay, HEADERS);
	}
//	private void ngayChuNhat() {
//		//chủ nhật trong jdatechooser là 0
//		int ngayChuNhat = dtNgayChamCongCC.getDate().getDay();
//		if(ngayChuNhat == 0) {
//			System.out.println("Ngày Chủ Nhật");
//		}
//	}
	private void themSuKien() {
		
		dtNgayChamCongCC.setEnabled(true);
		dtNgayChamCongCC.setDate(new Date());
		dsCCNV = chamCongNhanVienDAO.layDanhSachCCNV();
		dsNV = chamCongNhanVienDAO.layDanhSachNhanVienChuaChamCong(new java.sql.Date(new Date().getTime()));
		updateChamCongNhanVienModelTable(dsCCNV, HEADERS);
		updateNhanVienModelTable(dsNV, HEADERSNV);

		tblChamCong.addMouseListener(new MouseAdapter() {
			@SuppressWarnings("deprecation")
			@Override
			public void mouseClicked(MouseEvent e) {

				// TODO Auto-generated method stub
				String maChamCong = (String) tblChamCong.getModel().getValueAt(tblChamCong.getSelectedRow(), 0);
				//				System.out.println(index);
				if(maChamCong != null) {
					BangChamCongNhanVien chamCongNhanVien = null;
					try {
						chamCongNhanVien = chamCongNhanVienDAO.timThongTinChamCongNhanVien(maChamCong);
						fillThongTinChamCongNV(chamCongNhanVien);
						if (chamCongNhanVien.getTinhTrangChamCong().equalsIgnoreCase("Nửa công")
						        && !chamCongNhanVien.getTrangThai().equalsIgnoreCase("Nghỉ có phép")
						        && chamCongNhanVien.getNgayChamCong().compareTo(dtNgayChamCong.getDate()) <= 0) {
							btnChamGioVe.setEnabled(true);
							txtSoGioLamThemCC.setEditable(true);
							txtSoGioLamThemCC.setBackground(new Color(255,255,255));
						}
						else {
							btnChamGioVe.setEnabled(false);
							txtSoGioLamThemCC.setEditable(false);
							txtSoGioLamThemCC.setBackground(new Color(242,242,242));
						}


					} catch (Exception e2) {
						// TODO: handle exception
						e2.printStackTrace();
					}
				}
				
			}
		});
		//checkbox lịch hôm nay
		cbLichHomNay.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				if(cbLichHomNay.isSelected() == true) {
					danhSachChamCongHomNay();
				}
				else {
					updateChamCongNhanVienModelTable(dsCCNV, HEADERS);
				}
				
			}
		});
		
		//listener ngày chấm công
		dtNgayChamCongCC.addPropertyChangeListener(new PropertyChangeListener() {
		    @Override
		    public void propertyChange(PropertyChangeEvent evt) {
		    	
		        // Kiểm tra xem thuộc tính đã thay đổi có phải là ngày không
		        if ("date".equals(evt.getPropertyName())) {
		            // Lấy ngày mới được chọn
		            Date ngay = (Date) evt.getNewValue();
					
					dsNV = chamCongNhanVienDAO.layDanhSachNhanVienChuaChamCong(new java.sql.Date(ngay.getTime()));
					updateNhanVienModelTable(dsNV, HEADERSNV);
					if(cbLichHomNay.isSelected() == true) {
						danhSachChamCongHomNay();
					}
					
		            
		            
		        }
		      //kiem tra ngay ChuNhat
//		    	ngayChuNhat();
		    }
		});
		
		btnHuongDan.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				try {
					btnHuongDanActionPerformed(e);

				} catch (Exception e2) {
					// TODO: handle exception
					e2.printStackTrace();
				}
			}
				private void btnHuongDanActionPerformed(ActionEvent evt) throws Exception {
			        ImageIcon imageIcon = new ImageIcon(setting.PathSetting.PATH_IMAGE_HUONGDAN + "ChamCongNV.jpg");
			        
			        JPanel imagePanel = new JPanel();
			        imagePanel.setLayout(new BoxLayout(imagePanel, BoxLayout.Y_AXIS));
			        
			        JLabel imageLabel1 = new JLabel(imageIcon);
			        imagePanel.add(imageLabel1);
			        
			        JScrollPane scrollPane = new JScrollPane(imagePanel);
			        scrollPane.setPreferredSize(new Dimension(1200, 700));
			        
			        scrollPane.getVerticalScrollBar().setUnitIncrement(20);
			        scrollPane.getVerticalScrollBar().setBlockIncrement(100);
			        
			        JOptionPane.showMessageDialog(null, scrollPane, "Hướng dẫn thêm nhân viên", JOptionPane.PLAIN_MESSAGE);
				}
			});
		
		btnChamGioDen.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnChamCongDenActionPerformed(evt);
				
			}
			private void btnChamCongDenActionPerformed(java.awt.event.ActionEvent evt) {
				try {
					
					
					
					
					if(tblNhanVien.getSelectedRow() != -1) {
						BangChamCongNhanVien chamCongNhanVien = layDuLieuDeChamCong();
						if(chamCongNhanVien != null)
							chamCongNhanVienDAO.themChamCongNhanVien(chamCongNhanVien);
						dsCCNV = chamCongNhanVienDAO.layDanhSachCCNV();
						//neu dang tich hom nay checkbox
						if(cbLichHomNay.isSelected() == true) {
							danhSachChamCongHomNay();
						}
						else {
							updateChamCongNhanVienModelTable(dsCCNV, HEADERS);
						}
						//xoa nhan vien da cham cong ra khỏi bảng nhân viên
						System.out.println("Size trước remove" + dsNV.size());
						dsNV.remove(tblNhanVien.getSelectedRow());
						System.out.println("Size sau remove" + dsNV.size());
						updateNhanVienModelTable(dsNV, HEADERSNV);
						
						//cap nhật danh sách nhân viên

					}
					else {
						JOptionPane.showMessageDialog(null, "Chưa chọn nhân viên");
					}
					
				} catch (Exception e2) {
					// TODO: handle exception
					e2.printStackTrace();
				}
			}                                           

		});
		btnChamGioVe.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnChamCongVeActionPerformed(evt);
			}
			private void btnChamCongVeActionPerformed(java.awt.event.ActionEvent evt) {
				try {
					BangChamCongNhanVien chamCongNhanVienLanHai = getDuLieuTuTextField();
					double soGioLamThem = Double.parseDouble(txtSoGioLamThemCC.getText().trim().isEmpty()? "0" : txtSoGioLamThemCC.getText().trim());
					
					if(soGioLamThem <=6) {
						chamCongNhanVienLanHai.setSoGioLamThem(soGioLamThem);
						chamCongNhanVienLanHai.setTinhTrangChamCong("Đủ công");
						if(chamCongNhanVienLanHai != null)
							chamCongNhanVienDAO.capNhatChamCongNV(chamCongNhanVienLanHai);

						dsCCNV = chamCongNhanVienDAO.layDanhSachCCNV();
						if(cbLichHomNay.isSelected() == true) {
							danhSachChamCongHomNay();
						}
						else {
							updateChamCongNhanVienModelTable(dsCCNV, HEADERS);
						}
						
						txtSoGioLamThemCC.setText("");
					}
					else
						JOptionPane.showMessageDialog(null, "Nhân viên làm thêm tối đa 6 tiếng một ngày");
					


				} catch (Exception e2) {
					// TODO: handle exception
					e2.printStackTrace();
				}
			}                                          
		});
	}

	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrChamCong = new javax.swing.JScrollPane();
        tblChamCong = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        dtNgayChamCongCC = new com.toedter.calendar.JDateChooser();
        lblNgayChamCongCC = new javax.swing.JLabel();
        lblSoGioLamThemCC = new javax.swing.JLabel();
        btnChamGioVe = new javax.swing.JButton();
        lblNgayChamCong = new javax.swing.JLabel();
        lblTinhTrang = new javax.swing.JLabel();
        lblTenNhanVien = new javax.swing.JLabel();
        lblMaNhanVien = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbTinhTrangCC = new javax.swing.JComboBox<>();
        txtSoGioLamThemCC = new javax.swing.JTextField();
        txtMaNhanVien = new javax.swing.JTextField();
        lblMaNguoiChamCong = new javax.swing.JLabel();
        txtMaNguoiChamCong = new javax.swing.JTextField();
        dtNgayChamCong = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        lblTinhTrangCC = new javax.swing.JLabel();
        cmbTinhTrang = new javax.swing.JComboBox<>();
        lblMaNguoiChamCong1 = new javax.swing.JLabel();
        txtTenNguoiChamCong = new javax.swing.JTextField();
        txtTenNhanVien1 = new javax.swing.JTextField();
        btnChamGioDen = new javax.swing.JButton();
        lblSoGioLamThem = new javax.swing.JLabel();
        txtSoGioLamThem = new javax.swing.JTextField();
        lblLichHomNay = new javax.swing.JLabel();
        cmbTinhTrangCong = new javax.swing.JComboBox<>();
        cbLichHomNay = new javax.swing.JCheckBox();
        lblTinhTrangCong1 = new javax.swing.JLabel();
        btnHuongDan = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        scrChamCong.setBackground(new java.awt.Color(255, 255, 255));
        scrChamCong.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bảng chấm công", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16))); // NOI18N

        tblChamCong.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tblChamCong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã chấm công", "Mã nhân viên", "Họ và tên", "Ngày chấm công", "Ca làm", "Tình trạng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblChamCong.setMinimumSize(null);
        tblChamCong.setSelectionBackground(new java.awt.Color(51, 153, 255));
        scrChamCong.setViewportView(tblChamCong);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách nhân viên hành chính"));

        tblNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Ca làm"
            }
        ));
        jScrollPane1.setViewportView(tblNhanVien);

        dtNgayChamCongCC.setDateFormatString("yyyy-MM-dd");
        dtNgayChamCongCC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblNgayChamCongCC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNgayChamCongCC.setText("Ngày chấm công:");

        lblSoGioLamThemCC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSoGioLamThemCC.setText("Số giờ làm thêm:");

        btnChamGioVe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnChamGioVe.setText("Chấm giờ về");
        btnChamGioVe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblNgayChamCong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNgayChamCong.setText("Ngày chấm công:");

        lblTinhTrang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTinhTrang.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTinhTrang.setText("Tình trạng:");

        lblTenNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTenNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTenNhanVien.setText("Tên nhân viên:");

        lblMaNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMaNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMaNhanVien.setText("Mã nhân viên:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("THÔNG TIN CHI TIẾT CHẤM CÔNG NHÂN VIÊN HÀNH CHÍNH");

        cmbTinhTrangCC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbTinhTrangCC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đi đúng giờ", "Đi trễ", "Nghỉ có phép" }));

        txtSoGioLamThemCC.setEditable(false);
        txtSoGioLamThemCC.setBackground(new java.awt.Color(204, 204, 204));
        txtSoGioLamThemCC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSoGioLamThemCC.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));

        txtMaNhanVien.setEditable(false);
        txtMaNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        txtMaNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMaNhanVien.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));

        lblMaNguoiChamCong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMaNguoiChamCong.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMaNguoiChamCong.setText("Mã người chấm công:");

        txtMaNguoiChamCong.setEditable(false);
        txtMaNguoiChamCong.setBackground(new java.awt.Color(255, 255, 255));
        txtMaNguoiChamCong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMaNguoiChamCong.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));

        dtNgayChamCong.setBackground(new java.awt.Color(255, 255, 255));
        dtNgayChamCong.setEnabled(false);
        dtNgayChamCong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CHẤM CÔNG NHÂN VIÊN");

        lblTinhTrangCC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTinhTrangCC.setText("Tình trạng:");

        cmbTinhTrang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbTinhTrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Đi đúng giờ", "Đi trễ", "Nghỉ có phép" }));
        cmbTinhTrang.setToolTipText("");
        cmbTinhTrang.setEnabled(false);

        lblMaNguoiChamCong1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMaNguoiChamCong1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMaNguoiChamCong1.setText("Tên người chấm công:");

        txtTenNguoiChamCong.setEditable(false);
        txtTenNguoiChamCong.setBackground(new java.awt.Color(255, 255, 255));
        txtTenNguoiChamCong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTenNguoiChamCong.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));

        txtTenNhanVien1.setEditable(false);
        txtTenNhanVien1.setBackground(new java.awt.Color(255, 255, 255));
        txtTenNhanVien1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTenNhanVien1.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));

        btnChamGioDen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnChamGioDen.setText("Chấm giờ đến");
        btnChamGioDen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblSoGioLamThem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSoGioLamThem.setText("Số giờ làm thêm:");

        txtSoGioLamThem.setEditable(false);
        txtSoGioLamThem.setBackground(new java.awt.Color(255, 255, 255));
        txtSoGioLamThem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSoGioLamThem.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));

        lblLichHomNay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLichHomNay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLichHomNay.setText("Lịch hôm nay");

        cmbTinhTrangCong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbTinhTrangCong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Nữa công", "Đủ công" }));
        cmbTinhTrangCong.setEnabled(false);

        cbLichHomNay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLichHomNayActionPerformed(evt);
            }
        });

        lblTinhTrangCong1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTinhTrangCong1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTinhTrangCong1.setText("Tình trạng Công:");

        btnHuongDan.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        btnHuongDan.setText("?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                .addComponent(btnHuongDan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(87, 87, 87)
                                        .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTenNhanVien)
                                        .addGap(87, 87, 87)
                                        .addComponent(txtTenNhanVien1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTinhTrang)
                                        .addGap(116, 116, 116)
                                        .addComponent(cmbTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNgayChamCong)
                                        .addGap(61, 61, 61)
                                        .addComponent(dtNgayChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblSoGioLamThem)
                                        .addGap(64, 64, 64)
                                        .addComponent(txtSoGioLamThem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblMaNguoiChamCong)
                                        .addGap(26, 26, 26)
                                        .addComponent(txtMaNguoiChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblMaNguoiChamCong1)
                                        .addGap(23, 23, 23)
                                        .addComponent(txtTenNguoiChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblNgayChamCongCC)
                        .addGap(11, 11, 11)
                        .addComponent(dtNgayChamCongCC, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139)
                        .addComponent(lblSoGioLamThemCC)
                        .addGap(14, 14, 14)
                        .addComponent(txtSoGioLamThemCC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(250, 250, 250)
                        .addComponent(lblTinhTrangCong1)
                        .addGap(68, 68, 68)
                        .addComponent(cmbTinhTrangCong, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblTinhTrangCC)
                        .addGap(26, 26, 26)
                        .addComponent(cmbTinhTrangCC, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnChamGioDen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(240, 240, 240)
                        .addComponent(btnChamGioVe, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1550, 1550, 1550)
                        .addComponent(lblLichHomNay)
                        .addGap(8, 8, 8)
                        .addComponent(cbLichHomNay, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(scrChamCong)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenNhanVien1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNgayChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtNgayChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSoGioLamThem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoGioLamThem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaNguoiChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaNguoiChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaNguoiChamCong1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenNguoiChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHuongDan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNgayChamCongCC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtNgayChamCongCC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoGioLamThemCC, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSoGioLamThemCC)
                            .addComponent(lblTinhTrangCong1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTinhTrangCong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblTinhTrangCC))
                    .addComponent(cmbTinhTrangCC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChamGioDen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChamGioVe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLichHomNay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbLichHomNay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrChamCong, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbLichHomNayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLichHomNayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLichHomNayActionPerformed
	////////

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChamGioDen;
    private javax.swing.JButton btnChamGioVe;
    private javax.swing.JButton btnHuongDan;
    private javax.swing.JCheckBox cbLichHomNay;
    private javax.swing.JComboBox<String> cmbTinhTrang;
    private javax.swing.JComboBox<String> cmbTinhTrangCC;
    private javax.swing.JComboBox<String> cmbTinhTrangCong;
    private com.toedter.calendar.JDateChooser dtNgayChamCong;
    private com.toedter.calendar.JDateChooser dtNgayChamCongCC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLichHomNay;
    private javax.swing.JLabel lblMaNguoiChamCong;
    private javax.swing.JLabel lblMaNguoiChamCong1;
    private javax.swing.JLabel lblMaNhanVien;
    private javax.swing.JLabel lblNgayChamCong;
    private javax.swing.JLabel lblNgayChamCongCC;
    private javax.swing.JLabel lblSoGioLamThem;
    private javax.swing.JLabel lblSoGioLamThemCC;
    private javax.swing.JLabel lblTenNhanVien;
    private javax.swing.JLabel lblTinhTrang;
    private javax.swing.JLabel lblTinhTrangCC;
    private javax.swing.JLabel lblTinhTrangCong1;
    private javax.swing.JScrollPane scrChamCong;
    private javax.swing.JTable tblChamCong;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtMaNguoiChamCong;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtSoGioLamThem;
    private javax.swing.JTextField txtSoGioLamThemCC;
    private javax.swing.JTextField txtTenNguoiChamCong;
    private javax.swing.JTextField txtTenNhanVien1;
    // End of variables declaration//GEN-END:variables
}
