/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author hoangtruong
 */
public class MenuTimKiemCongNhan extends javax.swing.JPanel {

    /**
     * Creates new form FrmTimKiem
     */
    public MenuTimKiemCongNhan() {
        initComponents();
        themSuKien();
    }

    private void themSuKien() {
    	btnTimKiemCN.setEnabled(false);
    	pnlBodyTim.add(new TimKiemCN());
    	
    	btnTimKiemChamCongCN.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				btnTimKiemChamCongCNActionPerformed(e);
				
			}
			private void btnTimKiemChamCongCNActionPerformed(ActionEvent evt) {
				pnlBodyTim.removeAll();
				pnlBodyTim.add(new TimKiemChamCongCongNhan());
				pnlBodyTim.repaint();
				pnlBodyTim.revalidate();
				btnTimKiemChamCongCN.setEnabled(false);
				btnTimKiemPhanCongCN.setEnabled(true);
				btnTimKiemCN.setEnabled(true);
			}
			
		});
    	
    	btnTimKiemPhanCongCN.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				btnTimKiemPhanCongCNActionPerformed(e);
				
			}
			private void btnTimKiemPhanCongCNActionPerformed(ActionEvent evt) {
				pnlBodyTim.removeAll();
				pnlBodyTim.add(new TimKiemPhanCong());
				pnlBodyTim.repaint();
				pnlBodyTim.revalidate();
				btnTimKiemChamCongCN.setEnabled(true);
				btnTimKiemPhanCongCN.setEnabled(false);
				btnTimKiemCN.setEnabled(true);
			}
			
		});
    	
    	btnTimKiemCN.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				btnTimKiemNhanVienActionPerformed(e);
				
			}
			private void btnTimKiemNhanVienActionPerformed(ActionEvent evt) {
				pnlBodyTim.removeAll();
				pnlBodyTim.add(new TimKiemCN());
				pnlBodyTim.repaint();
				pnlBodyTim.revalidate();
				btnTimKiemChamCongCN.setEnabled(true);
				btnTimKiemPhanCongCN.setEnabled(true);
				btnTimKiemCN.setEnabled(false);
			}
			
		});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBodyTim = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnTimKiemChamCongCN = new javax.swing.JButton();
        btnTimKiemCN = new javax.swing.JButton();
        btnTimKiemPhanCongCN = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        pnlBodyTim.setBackground(new java.awt.Color(255, 255, 255));
        pnlBodyTim.setLayout(new java.awt.BorderLayout());
        add(pnlBodyTim, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TÌM KIẾM");

        btnTimKiemChamCongCN.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnTimKiemChamCongCN.setText("Tìm chấm công công nhân");
        btnTimKiemChamCongCN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, new java.awt.Color(204, 204, 204)));

        btnTimKiemCN.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnTimKiemCN.setText("Tìm công nhân");
        btnTimKiemCN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, new java.awt.Color(204, 204, 204)));

        btnTimKiemPhanCongCN.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnTimKiemPhanCongCN.setText("Tìm phân công công nhân");
        btnTimKiemPhanCongCN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnTimKiemCN, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnTimKiemChamCongCN, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTimKiemPhanCongCN, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 150, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTimKiemCN, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTimKiemChamCongCN, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTimKiemPhanCongCN, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimKiemCN;
    private javax.swing.JButton btnTimKiemChamCongCN;
    private javax.swing.JButton btnTimKiemPhanCongCN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnlBodyTim;
    // End of variables declaration//GEN-END:variables
}
