/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author hoangtruong
 */
public class MenuTimKiemSanPham extends javax.swing.JPanel {

    /**
     * Creates new form FrmTimKiem
     */
    public MenuTimKiemSanPham() {
        initComponents();
        themSuKien();
    }
    
    private void themSuKien() {
    	btnTimKiemSanPham.setEnabled(false);
    	pnlBodyTim.add(new TimKiemSP());
    	
    	btnTimKiemCongDoan.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				btnTimKiemCongDoanActionPerformed(e);
				
			}
			private void btnTimKiemCongDoanActionPerformed(ActionEvent evt) {
				pnlBodyTim.removeAll();
				pnlBodyTim.add(new TimKiemCongDoan());
				pnlBodyTim.repaint();
				pnlBodyTim.revalidate();
				btnTimKiemCongDoan.setEnabled(false);
				btnTimKiemSanPham.setEnabled(true);
			}
			
		});
    	
    	btnTimKiemSanPham.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				btnTimKiemSanPhamActionPerformed(e);
				
			}
			private void btnTimKiemSanPhamActionPerformed(ActionEvent evt) {
				pnlBodyTim.removeAll();
				pnlBodyTim.add(new TimKiemSP());
				pnlBodyTim.repaint();
				pnlBodyTim.revalidate();
				btnTimKiemSanPham.setEnabled(false);
		    	btnTimKiemCongDoan.setEnabled(true);
			}
			
		});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBodyTim = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnTimKiemCongDoan = new javax.swing.JButton();
        btnTimKiemSanPham = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        pnlBodyTim.setBackground(new java.awt.Color(255, 255, 255));
        pnlBodyTim.setLayout(new java.awt.BorderLayout());
        add(pnlBodyTim, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TÌM KIẾM");

        btnTimKiemCongDoan.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnTimKiemCongDoan.setText("Tìm công đoạn");
        btnTimKiemCongDoan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, new java.awt.Color(204, 204, 204)));

        btnTimKiemSanPham.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnTimKiemSanPham.setText("Tìm sản phẩm");
        btnTimKiemSanPham.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnTimKiemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnTimKiemCongDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 449, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTimKiemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiemCongDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimKiemCongDoan;
    private javax.swing.JButton btnTimKiemSanPham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnlBodyTim;
    // End of variables declaration//GEN-END:variables
}
