/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

import javax.swing.BoxLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.border.MatteBorder;
import javax.swing.event.PopupMenuEvent;
import javax.swing.event.PopupMenuListener;

import dao.DiaChiDAO;
import dao.NhanVienDAO;
import dao.TaiKhoanDAO;
import entity.DiaChi;
import entity.NhanVien;
import entity.TaiKhoan;
import javax.swing.UIManager;
import setting.PathSetting;
import tablemodels.NhanVienTableModel;

/**
 *
 * @author Hoang Truong
 */
public class QuanLyNV extends javax.swing.JPanel {

	/**
	 * Creates new form QuanLyNV
	 */
	private NhanVienDAO nhanVienDAO;
	private NhanVienTableModel nhanVienTableModel;
	private DiaChiDAO diaChiDAO;
	private TaiKhoanDAO taiKhoanDAO;
	private List<NhanVien> dsNV;
	private boolean trangThaiThem;
	private NhanVien nhanVienLogin;
	private static final String[] HEADERS = { "Mã nhân viên", "Tên nhân viên", "Ngày sinh", "Email", "Số điện thoại",
			"Địa chỉ", "Ngày vào làm", "Giới tính", "Vai trò", "Trình độ", "Ngoại Ngữ" };

	public QuanLyNV(NhanVien nvLogin) {
		nhanVienDAO = new NhanVienDAO();
		diaChiDAO = new DiaChiDAO();
		taiKhoanDAO = new TaiKhoanDAO();
		trangThaiThem = false;
		this.nhanVienLogin = nvLogin;
		initComponents();
		listenerInput();
		themSuKien();
		phimTatChoButton();
		updateComboboxTinh();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void listenerInput() {
		txtSoDienThoai.addKeyListener(new SoKeyListener());
		txtTenNhanVien.addKeyListener(new ChuoiKeyListener());
	}

	private void phimTatChoButton() {
		btnThem.setMnemonic('T');
		btnXoa.setMnemonic('X');
		btnSua.setMnemonic('S');

	}

	private void setWidthTable() {
		if (tblNhanVien.getColumnModel().getColumnCount() > 0) {

			tblNhanVien.getColumnModel().getColumn(0).setMinWidth(60);
			tblNhanVien.getColumnModel().getColumn(1).setMinWidth(85);
			tblNhanVien.getColumnModel().getColumn(2).setMinWidth(65);
			tblNhanVien.getColumnModel().getColumn(3).setMinWidth(90);
			tblNhanVien.getColumnModel().getColumn(4).setMinWidth(70);
			tblNhanVien.getColumnModel().getColumn(5).setMinWidth(309);
			tblNhanVien.getColumnModel().getColumn(6).setMinWidth(68);
			tblNhanVien.getColumnModel().getColumn(7).setMinWidth(40);
			tblNhanVien.getColumnModel().getColumn(8).setMinWidth(59);
			tblNhanVien.getColumnModel().getColumn(9).setMinWidth(40);
			tblNhanVien.getColumnModel().getColumn(10).setMinWidth(40);

		}
	}

	// them su kien cho UI Quan Ly Nhan Vien
	private void updateModelTable(List<NhanVien> dsNV, String[] headers) {
		nhanVienTableModel = new NhanVienTableModel(headers, dsNV);
		tblNhanVien.setModel(nhanVienTableModel);
		setWidthTable();
		tblNhanVien.updateUI();

	}

	private void updateComboboxTinh() {
		List<String> dsTam = diaChiDAO.layDanhSachTinh();

		String[] dsTinh = new String[dsTam.size()];
		dsTam.toArray(dsTinh);
		cmbTinhTP.setModel(new DefaultComboBoxModel<String>(dsTinh));
		cmbTinhTP.updateUI();
		updateComboboxHuyen();
	}

	private void updateComboboxHuyen() {
		String tinh = (String) cmbTinhTP.getSelectedItem();
		List<String> dsTam = diaChiDAO.layDSHuyenTheoTinh(tinh);
		String[] dsHuyen = new String[dsTam.size()];
		dsTam.toArray(dsHuyen);
		cmbQuanHuyen.setModel(new DefaultComboBoxModel<String>(dsHuyen));
		cmbQuanHuyen.updateUI();

		updateComboboxXa();
	}

	private void updateComboboxXa() {
		String tinh = (String) cmbTinhTP.getSelectedItem();
		String huyen = (String) cmbQuanHuyen.getSelectedItem();
		List<String> dsTam = diaChiDAO.layDSXaTheoHuyenTinh(tinh, huyen);
		String[] dsXa = new String[dsTam.size()];
		dsTam.toArray(dsXa);
		cmbPhuongXa.setModel(new DefaultComboBoxModel<String>(dsXa));
		cmbPhuongXa.updateUI();
	}

	private void xoaRong() {
		txtTenNhanVien.setText("");
		txtSoDienThoai.setText("");
		txtEmail.setText("");
		cmbVaiTro.setSelectedItem("All");
		cmbGioiTinh.setSelectedItem("All");
		dtNgaySinh.setDate(null);
		dtNgayVaoLam.setDate(null);
		lblAnhDaiDien.setIcon(new javax.swing.ImageIcon(PathSetting.PATH_IMAGE_NHANVIEN + "noimage.png"));
		cmbTrinhDoChuyenMon.setSelectedItem("All");
		cmbTrinhDoNgoaiNgu.setSelectedItem("All");
	}

	private void batTextfield() {
		txtMaNhanVien.setEditable(false);
		txtTenNhanVien.setEditable(true);
		txtEmail.setEditable(true);
		txtSoDienThoai.setEditable(true);
		cmbGioiTinh.setEnabled(true);
		cmbVaiTro.setEnabled(true);
		cmbTinhTP.setEnabled(true);
		cmbQuanHuyen.setEnabled(true);
		cmbPhuongXa.setEnabled(true);
		dtNgaySinh.setEnabled(true);
		dtNgayVaoLam.setEnabled(true);
		btnChonHinhAnh.setEnabled(true);
		cmbTrinhDoChuyenMon.setEnabled(true);
		cmbTrinhDoNgoaiNgu.setEnabled(true);
	}

	private void tatTextfield() {
		txtMaNhanVien.setEditable(false);
		txtTenNhanVien.setEditable(false);
		txtEmail.setEditable(false);
		txtSoDienThoai.setEditable(false);
		cmbGioiTinh.setEnabled(false);
		cmbVaiTro.setEnabled(false);
		cmbTinhTP.setEnabled(false);
		cmbQuanHuyen.setEnabled(false);
		cmbPhuongXa.setEnabled(false);
		dtNgaySinh.setEnabled(false);
		dtNgayVaoLam.setEnabled(false);
		btnChonHinhAnh.setEnabled(false);
		cmbTrinhDoChuyenMon.setEnabled(false);
		cmbTrinhDoNgoaiNgu.setEnabled(false);
	}

	private boolean kiemTraDL() {
		boolean kt = true;
		String tenNV = txtTenNhanVien.getText().trim();
		String soDienThoai = txtSoDienThoai.getText().trim();
		String email = txtEmail.getText().trim();
		String trinhDoChuyenMon = cmbTrinhDoChuyenMon.getSelectedItem().toString();
		String trinhDoNgoaiNgu = cmbTrinhDoNgoaiNgu.getSelectedItem().toString();
		String gioiTinh = cmbGioiTinh.getSelectedItem().toString();
		String vaiTro = cmbVaiTro.getSelectedItem().toString();
		Date ngaySinh = null;
		try {
			ngaySinh = dtNgaySinh.getDate();
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}
		Date ngayHienTai = new Date();
		Date ngayVaoLam = null;
		try {
			ngayVaoLam = dtNgayVaoLam.getDate();
		} catch (Exception e) {
			// TODO: handle exception
		}
		if (tenNV.isBlank()) {
			JOptionPane.showMessageDialog(null, "Tên nhân viên không được để trống");
			txtTenNhanVien.requestFocus();
			kt = false;
		} else if (!tenNV.matches("^([A-ZĐÂÁƯ][a-zỳọáầảấờễàạằệếýộậốũứĩõúữịỗìềểẩớặòùồợãụủíỹắẫựỉỏừỷởóéửỵẳẹèẽổ"
				+ "ẵẻỡơôưăêâđ]+)((\\s[A-ZĐÂÁƯ][a-zỳọáầảấờễàạằệếýộậốũứĩõúữịỗìềểẩớặòùồợãụủíỹắẫựỉỏừỷởóéửỵẳẹèẽổẵẻỡơôưăêâđ]+){1,})$")) {
			JOptionPane.showMessageDialog(null, "Tên không hợp lệ");
			txtTenNhanVien.requestFocus();
			kt = false;
		} else if (soDienThoai.isBlank()) {
			JOptionPane.showMessageDialog(null, "Không để trống số điện thoại");
			txtSoDienThoai.requestFocus();
			kt = false;
		} else if (!soDienThoai.matches("^0\\d{9}$")) {
			JOptionPane.showMessageDialog(null, "Số điện thoại gồm 10 số, bắt đầu bằng số 0");
			txtSoDienThoai.requestFocus();
			kt = false;
		} else if (email.isBlank()) {
			JOptionPane.showMessageDialog(null, "Không để trống email");
			txtEmail.requestFocus();
			kt = false;
		} else if (!email.matches("^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$")) {
			JOptionPane.showMessageDialog(null, "Email sai định dạng");
			txtEmail.requestFocus();
			kt = false;
		} else if (trinhDoChuyenMon.equals("All")) {
			JOptionPane.showMessageDialog(null, "Chưa chọn trình độ chuyên môn");
			kt = false;
		} else if (trinhDoNgoaiNgu.equals("All")) {
			JOptionPane.showMessageDialog(null, "Chưa chọn trình độ ngoại ngữ");
			kt = false;
		} else if (cmbTinhTP.getSelectedItem().toString().equals("Tỉnh/Thành Phố")) {
			JOptionPane.showMessageDialog(null, "Chưa chọn tỉnh/thành phố");
			kt = false;
		} else if (cmbQuanHuyen.getSelectedItem().toString().equals("Quận, Huyện")) {
			JOptionPane.showMessageDialog(null, "Chưa chọn quận/huyện");
			kt = false;
		} else if (cmbPhuongXa.getSelectedItem().toString().equals("Phường, Xã")) {
			JOptionPane.showMessageDialog(null, "Chưa chọn phường/xã");
			kt = false;
		} else if (dtNgaySinh.getDate() == null) {
			JOptionPane.showMessageDialog(null, "Chưa chọn ngày sinh");
			kt = false;
		} else if (ngaySinh.after(ngayHienTai)) {
			JOptionPane.showMessageDialog(null, "Ngày sinh không được sau ngày hiện tại");
			kt = false;
		} else if (dtNgayVaoLam.getDate() == null) {
			JOptionPane.showMessageDialog(null, "Chưa chọn ngày vào làm");
			kt = false;
		} else if (ngaySinh.after(ngayVaoLam)) {
			JOptionPane.showMessageDialog(null, "Ngày sinh không được sau ngày vào làm");
			kt = false;
		} else if (ngayVaoLam.after(ngayHienTai)) {
			JOptionPane.showMessageDialog(null, "Ngày vào làm không được sau ngày hiện tại");
			kt = false;
		} else if (ngayVaoLam.getYear() - ngaySinh.getYear() < 18) {
			JOptionPane.showMessageDialog(null, "Nhân viên phải từ 18 tuổi trở lên");
			kt = false;
		} else if (vaiTro.equals("All")) {
			JOptionPane.showMessageDialog(null, "Chưa chọn vai trò");
			kt = false;
		}
		return kt;
	}

	private NhanVien getDuLieuTuTextField() throws Exception {
		if (kiemTraDL()) {
			String maNV = txtMaNhanVien.getText().trim();
			String tenNV = txtTenNhanVien.getText().trim();
			String soDienThoai = txtSoDienThoai.getText().trim();
			String email = txtEmail.getText().trim();
			String trinhDoChuyenMon = cmbTrinhDoChuyenMon.getSelectedItem().toString();
			String trinhDoNgoaiNgu = cmbTrinhDoNgoaiNgu.getSelectedItem().toString();
			String gioiTinh = cmbGioiTinh.getSelectedItem().toString();
			String vaiTro = cmbVaiTro.getSelectedItem().toString();
			Date ngaySinh = null;
			try {
				ngaySinh = dtNgaySinh.getDate();
			} catch (Exception e) {
				// TODO: handle exception
				e.printStackTrace();
			}
			Date ngayVaoLam = null;
			try {
				ngayVaoLam = dtNgayVaoLam.getDate();
			} catch (Exception e) {
				// TODO: handle exception
			}
			DiaChi diaChi = diaChiDAO.getDiaChiTheoTinhHuyenXa(cmbTinhTP.getSelectedItem().toString(),
					cmbQuanHuyen.getSelectedItem().toString(), cmbPhuongXa.getSelectedItem().toString());
			String hinhAnh = lblAnhDaiDien.getIcon().toString();
			hinhAnh = hinhAnh.replace(PathSetting.PATH_IMAGE_NHANVIEN, "");
			NhanVien nhanVien = new NhanVien(maNV, tenNV, ngaySinh, email, soDienThoai, diaChi, ngayVaoLam, gioiTinh,
					vaiTro, hinhAnh, trinhDoChuyenMon, trinhDoNgoaiNgu);
			return nhanVien;
		}
		return null;
	}

	private void themSuKien() {
		dsNV = nhanVienDAO.layDanhSachNhanVien();
		updateModelTable(dsNV, HEADERS);
		tblNhanVien.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				// TODO Auto-generated method stub
				String maNhanVien = (String) tblNhanVien.getModel().getValueAt(tblNhanVien.getSelectedRow(), 0);
				if (maNhanVien != null) {
					NhanVien nv = null;
					try {
						if (!trangThaiThem) {
							nv = nhanVienDAO.timNhanVienBangMaNhanVien(maNhanVien);
							fillThongTinNhanVien(nv);
						}
					} catch (Exception e1) {
						e1.printStackTrace();
					}

				}
			}

			private void fillThongTinNhanVien(NhanVien nv) throws Exception {
				// TODO Auto-generated method stub
				txtTenNhanVien.setText(nv.getTenNhanVien());
				txtMaNhanVien.setText(nv.getMaNhanVien());
				txtSoDienThoai.setText(nv.getSoDienThoai());
				cmbTinhTP.setSelectedItem(nv.getDiaChi().getTinhTP());
				cmbQuanHuyen.addItem(nv.getDiaChi().getQuanHuyen());
				cmbQuanHuyen.setSelectedItem(nv.getDiaChi().getQuanHuyen());
				cmbPhuongXa.addItem(nv.getDiaChi().getPhuongXa());
				cmbPhuongXa.setSelectedItem(nv.getDiaChi().getPhuongXa());
				cmbVaiTro.setSelectedItem(nv.getVaiTro());
				cmbGioiTinh.setSelectedItem(nv.getGioiTinh().compareTo("Nữ") == 0 ? "Nữ" : "Nam");
				txtEmail.setText(nv.getEmail());
				dtNgaySinh.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(nv.getNgaySinh().toString()));
				dtNgayVaoLam.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(nv.getNgayVaoLam().toString()));
				lblAnhDaiDien.setIcon(new ImageIcon(PathSetting.PATH_IMAGE_NHANVIEN + nv.getAnhDaiDien()));
				cmbTrinhDoChuyenMon.setSelectedItem(nv.getTrinhDoChuyenMon());
				cmbTrinhDoNgoaiNgu.setSelectedItem(nv.getTrinhDoNgoaiNgu());
			}

		});
		// cap nhat lai combobox Huyen sau khi combobox tinh duoc select
		cmbTinhTP.addPopupMenuListener(new PopupMenuListener() {

			@Override
			public void popupMenuWillBecomeInvisible(PopupMenuEvent e) {
				// TODO Auto-generated method stub
				updateComboboxHuyen();

			}

			@Override
			public void popupMenuWillBecomeVisible(PopupMenuEvent e) {
				// TODO Auto-generated method stub

			}

			@Override
			public void popupMenuCanceled(PopupMenuEvent e) {
				// TODO Auto-generated method stub

			}

		});
		// cap nhat lai combobox xa sau khi combobox huyen duoc selected
		cmbQuanHuyen.addPopupMenuListener(new PopupMenuListener() {

			@Override
			public void popupMenuWillBecomeVisible(PopupMenuEvent e) {
				// TODO Auto-generated method stub

			}

			@Override
			public void popupMenuWillBecomeInvisible(PopupMenuEvent e) {
				// TODO Auto-generated method stub
				updateComboboxXa();

			}

			@Override
			public void popupMenuCanceled(PopupMenuEvent e) {
				// TODO Auto-generated method stub

			}
		});
		
		btnHuongDan.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				try {
					btnHuongDanActionPerformed(e);

				} catch (Exception e2) {
					// TODO: handle exception
					e2.printStackTrace();
				}
			}
				private void btnHuongDanActionPerformed(ActionEvent evt) throws Exception {
			        ImageIcon imageIcon = new ImageIcon(setting.PathSetting.PATH_IMAGE_HUONGDAN + "ThemNV1.jpg");
			        ImageIcon imageIcon1 = new ImageIcon(setting.PathSetting.PATH_IMAGE_HUONGDAN + "ThemNV2.jpg");
			        
			        JPanel imagePanel = new JPanel();
			        imagePanel.setLayout(new BoxLayout(imagePanel, BoxLayout.Y_AXIS));
			        
			        JLabel imageLabel1 = new JLabel(imageIcon);
			        imagePanel.add(imageLabel1);
			        JLabel imageLabel2 = new JLabel(imageIcon1);
			        imagePanel.add(imageLabel2);
			        JScrollPane scrollPane = new JScrollPane(imagePanel);
			        scrollPane.setPreferredSize(new Dimension(1200, 700));
			        
			        scrollPane.getVerticalScrollBar().setUnitIncrement(20);
			        scrollPane.getVerticalScrollBar().setBlockIncrement(100);
			        
			        JOptionPane.showMessageDialog(null, scrollPane, "Hướng dẫn thêm nhân viên", JOptionPane.PLAIN_MESSAGE);
				}
			});
		// bat su kien nut them
		btnThem.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				try {
					btnThemActionPerformed(e);

				} catch (Exception e2) {
					// TODO: handle exception
					e2.printStackTrace();
				}

			}

			private void btnThemActionPerformed(ActionEvent evt) throws Exception {
				updateComboboxTinh();
				xoaRong();
				batTextfield();
				trangThaiThem = true;
				pnlChucNangTo.removeAll();
				pnlChucNangTo.setLayout(new BorderLayout());
				PanelXacNhan pnlXacNhan = new PanelXacNhan();
				pnlChucNangTo.add(pnlXacNhan);
				txtMaNhanVien.setText(getNewMaNV());

				ActionListener listenerHuy = new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						trangThaiThem = false;
						pnlChucNangTo.removeAll();
						pnlChucNangTo.setLayout(new BorderLayout());
						pnlChucNangTo.add(pnlChucNang);
						pnlChucNangTo.updateUI();
						tatTextfield();
					}
				};

				ActionListener listenerXoaRong = new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						xoaRong();
					}
				};

				ActionListener listenerThem = new ActionListener() {
					@Override
					public void actionPerformed(ActionEvent e) {
						// TODO Auto-generated method stub
						try {
							NhanVien nhanVien = getDuLieuTuTextField();
							if (nhanVien != null) {
								nhanVienDAO.themNhanVien(nhanVien);
								if (nhanVien.getVaiTro().equalsIgnoreCase("Quản lý")
										|| nhanVien.getVaiTro().equalsIgnoreCase("Kế toán")) {
									String tenTK = nhanVien.getMaNhanVien();
									String matKhau = "123456";
									TaiKhoan taiKhoan = new TaiKhoan(tenTK, matKhau, nhanVien.getVaiTro(), nhanVien);
									taiKhoanDAO.themTaiKhoan(taiKhoan);

								}
								dsNV = nhanVienDAO.layDanhSachNhanVien();
								updateModelTable(dsNV, HEADERS);
								txtMaNhanVien.setText(getNewMaNV());
								xoaRong();
								JOptionPane.showMessageDialog(null, "Thêm thành công");

							}
						} catch (Exception e2) {
							e2.printStackTrace();
							// TODO: handle exception
						}

					}
				};

				pnlXacNhan.huyAddActionListener(listenerHuy);
				pnlXacNhan.xoaRongAddActionListener(listenerXoaRong);
				pnlXacNhan.xacNhanAddActionListener(listenerThem);
				pnlChucNangTo.repaint();
				pnlChucNangTo.revalidate();

			}

			private String getNewMaNV() throws Exception {
				String maNV = nhanVienDAO.getMaNhanVienCaoNhat();
				int maNVt = 1;
				if (maNV != null)
					maNVt = Integer.parseInt(maNV.replaceAll("\\D+", "")) + 1;
				return String.format("NV%06d", maNVt);
			}

		});

		btnXoa.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				try {
					btnXoaActionPerformed(e);

				} catch (Exception e2) {
					// TODO: handle exception
					e2.printStackTrace();
				}

			}

			private void btnXoaActionPerformed(ActionEvent evt) {
				// TODO add your handling code here:
				int selectedRow = tblNhanVien.getSelectedRow();
				if (selectedRow == -1) {
					JOptionPane.showMessageDialog(null, "Chọn nhân viên cần xóa");
					return;
				}
				try {
					String maNV = (String) tblNhanVien.getModel().getValueAt(tblNhanVien.getSelectedRow(), 0);
					int luaChon = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa không", "Xóa",
							JOptionPane.YES_OPTION, JOptionPane.NO_OPTION);
					if (luaChon == JOptionPane.YES_OPTION) {
						boolean ketQua = nhanVienDAO.xoaNhanVien(maNV);
						if (ketQua) {

							// cap nhat lai bang nhan vien
							dsNV = nhanVienDAO.layDanhSachNhanVien();
							updateModelTable(dsNV, HEADERS);
							xoaRong();
							JOptionPane.showMessageDialog(null, "Xóa thành công");

						} else {

							JOptionPane.showMessageDialog(null, "Xóa thất bại");
							xoaRong();
						}

					}

				} catch (Exception e) {
					// TODO: handle exception
					e.printStackTrace();
				}

			}
		});
		btnSua.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				btnSuaActionPerformed(evt);

			}

			private void btnSuaActionPerformed(ActionEvent evt) {
				// TODO add your handling code here:

				batTextfield();
				String huyenDangChon = cmbQuanHuyen.getSelectedItem().toString();
				String xaDangChon = cmbPhuongXa.getSelectedItem().toString();
				updateComboboxHuyen();

				cmbQuanHuyen.setSelectedItem(huyenDangChon);
				updateComboboxXa();
				cmbPhuongXa.setSelectedItem(xaDangChon);

				pnlChucNangTo.removeAll();
				pnlChucNangTo.setLayout(new BorderLayout());
				PanelXacNhan pnlXacNhan = new PanelXacNhan();
				pnlChucNangTo.add(pnlXacNhan);

				ActionListener listenerHuy = new ActionListener() {
					public void actionPerformed(ActionEvent evt) {
						trangThaiThem = false;
						pnlChucNangTo.removeAll();
						pnlChucNangTo.setLayout(new BorderLayout());
						pnlChucNangTo.add(pnlChucNang);
						pnlChucNangTo.updateUI();
						tatTextfield();
					}
				};

				ActionListener listenerXoaRong = new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						xoaRong();
					}
				};

				ActionListener listenerSua = new ActionListener() {

					@Override
					public void actionPerformed(ActionEvent e) {
						// TODO Auto-generated method stub
						try {
							NhanVien nhanVien = getDuLieuTuTextField();
							if (nhanVien != null) {
								int luaChon = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn sửa không", "Sửa",
										JOptionPane.YES_OPTION, JOptionPane.NO_OPTION);
								if (luaChon == JOptionPane.YES_OPTION) {

									boolean ketQua = nhanVienDAO.capNhatNhanVien(nhanVien);
									if (ketQua) {
										dsNV = nhanVienDAO.layDanhSachNhanVien();
										updateModelTable(dsNV, HEADERS);
										JOptionPane.showMessageDialog(null, "Cập nhật thành công");
									}
								}
							}

						} catch (Exception e2) {
							// TODO: handle exception
							e2.printStackTrace();
						}

					}

				};
				pnlXacNhan.huyAddActionListener(listenerHuy);
				pnlXacNhan.xoaRongAddActionListener(listenerXoaRong);
				pnlXacNhan.xacNhanAddActionListener(listenerSua);
				pnlChucNangTo.repaint();
				pnlChucNangTo.revalidate();

			}
		});
		btnChonHinhAnh.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				btnTimKiemActionPerformed(e);

			}

			private void btnTimKiemActionPerformed(ActionEvent evt) {
				JFileChooser j = new JFileChooser("icon\\NhanVien");
				int r = j.showSaveDialog(null);
				if (r == JFileChooser.APPROVE_OPTION)
					lblAnhDaiDien.setIcon(new javax.swing.ImageIcon(j.getSelectedFile().getAbsolutePath()));

			}

		});
	}

	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlQLNV = new javax.swing.JPanel();
        lblMaNhanVien = new javax.swing.JLabel();
        lblTenNhanVien = new javax.swing.JLabel();
        lblSoDienThoai = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtMaNhanVien = new javax.swing.JTextField();
        txtTenNhanVien = new javax.swing.JTextField();
        txtSoDienThoai = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblDiaChi = new javax.swing.JLabel();
        lblGioiTinh = new javax.swing.JLabel();
        lblNgaySinh = new javax.swing.JLabel();
        lblNgayVaoLam = new javax.swing.JLabel();
        lblVaiTro = new javax.swing.JLabel();
        cmbTinhTP = new javax.swing.JComboBox<>();
        cmbQuanHuyen = new javax.swing.JComboBox<>();
        cmbGioiTinh = new javax.swing.JComboBox<>();
        dtNgaySinh = new com.toedter.calendar.JDateChooser();
        dtNgayVaoLam = new com.toedter.calendar.JDateChooser();
        lblTieuDe = new javax.swing.JLabel();
        lblAnhDaiDien = new javax.swing.JLabel();
        cmbVaiTro = new javax.swing.JComboBox<>();
        scrTableNhanVien = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        btnChonHinhAnh = new javax.swing.JButton();
        pnlChucNangTo = new javax.swing.JPanel();
        pnlChucNang = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        cmbPhuongXa = new javax.swing.JComboBox<>();
        lblTrinhDoChuyenMon = new javax.swing.JLabel();
        cmbTrinhDoChuyenMon = new javax.swing.JComboBox<>();
        lblTrinhDoNgoaiNgu = new javax.swing.JLabel();
        cmbTrinhDoNgoaiNgu = new javax.swing.JComboBox<>();
        btnHuongDan = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        pnlQLNV.setBackground(new java.awt.Color(255, 255, 255));
        pnlQLNV.setPreferredSize(new java.awt.Dimension(1250, 475));

        lblMaNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMaNhanVien.setText("Mã nhân viên:");

        lblTenNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTenNhanVien.setText("Tên nhân viên:");

        lblSoDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSoDienThoai.setText("Số điện thoại:");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEmail.setText("Email:");

        txtMaNhanVien.setEditable(false);
        txtMaNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        txtMaNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMaNhanVien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtMaNhanVien.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));

        txtTenNhanVien.setEditable(false);
        txtTenNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        txtTenNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTenNhanVien.setBorder(null);
        txtTenNhanVien.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));

        txtSoDienThoai.setEditable(false);
        txtSoDienThoai.setBackground(new java.awt.Color(255, 255, 255));
        txtSoDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSoDienThoai.setBorder(null);
        txtSoDienThoai.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));

        txtEmail.setEditable(false);
        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtEmail.setBorder(null);
        txtEmail.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));

        lblDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDiaChi.setText("Địa chỉ:");

        lblGioiTinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGioiTinh.setText("Giới tính:");

        lblNgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNgaySinh.setText("Ngày sinh:");

        lblNgayVaoLam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNgayVaoLam.setText("Ngày vào làm:");

        lblVaiTro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblVaiTro.setText("Vai trò:");

        cmbTinhTP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbTinhTP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tỉnh/Thành phố" }));
        cmbTinhTP.setEnabled(false);

        cmbQuanHuyen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbQuanHuyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quận/Huyện" }));
        cmbQuanHuyen.setEnabled(false);

        cmbGioiTinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cmbGioiTinh.setEnabled(false);

        dtNgaySinh.setBackground(new java.awt.Color(255, 255, 255));
        dtNgaySinh.setEnabled(false);
        dtNgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        dtNgayVaoLam.setBackground(new java.awt.Color(255, 255, 255));
        dtNgayVaoLam.setEnabled(false);
        dtNgayVaoLam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblTieuDe.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTieuDe.setText("QUẢN LÝ NHÂN VIÊN");

        lblAnhDaiDien.setBackground(new java.awt.Color(0, 204, 153));
        lblAnhDaiDien.setForeground(new java.awt.Color(0, 255, 204));

        cmbVaiTro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbVaiTro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản lý", "Kế toán", "Nhân viên" }));
        cmbVaiTro.setEnabled(false);

        scrTableNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        scrTableNhanVien.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16))); // NOI18N

        tblNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã công nhân", "Tên công nhân", "Số điện thoại", "Email", "Địa chỉ", "Giới tính", "Ngày sinh", "Ngày vào làm", "Tổ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhanVien.setSelectionBackground(new java.awt.Color(51, 153, 255));
        scrTableNhanVien.setViewportView(tblNhanVien);

        btnChonHinhAnh.setText("Hình ảnh");
        btnChonHinhAnh.setEnabled(false);

        pnlChucNangTo.setBackground(new java.awt.Color(255, 255, 255));
        pnlChucNangTo.setLayout(new java.awt.BorderLayout());

        pnlChucNang.setBackground(new java.awt.Color(255, 255, 255));
        pnlChucNang.setPreferredSize(new java.awt.Dimension(698, 57));

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-add-20.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlChucNangLayout = new javax.swing.GroupLayout(pnlChucNang);
        pnlChucNang.setLayout(pnlChucNangLayout);
        pnlChucNangLayout.setHorizontalGroup(
            pnlChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChucNangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        pnlChucNangLayout.setVerticalGroup(
            pnlChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChucNangLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(pnlChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlChucNangTo.add(pnlChucNang, java.awt.BorderLayout.CENTER);

        cmbPhuongXa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbPhuongXa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phường/Xã" }));
        cmbPhuongXa.setEnabled(false);

        lblTrinhDoChuyenMon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTrinhDoChuyenMon.setText("Trình độ:");

        cmbTrinhDoChuyenMon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbTrinhDoChuyenMon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Đại học", "Cao đẳng", "Trung cấp" }));
        cmbTrinhDoChuyenMon.setEnabled(false);

        lblTrinhDoNgoaiNgu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTrinhDoNgoaiNgu.setText("Ngoại ngữ:");

        cmbTrinhDoNgoaiNgu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbTrinhDoNgoaiNgu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Sơ cấp", "Trung cấp", "Cao cấp" }));
        cmbTrinhDoNgoaiNgu.setEnabled(false);

        btnHuongDan.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        btnHuongDan.setText("?");

        javax.swing.GroupLayout pnlQLNVLayout = new javax.swing.GroupLayout(pnlQLNV);
        pnlQLNV.setLayout(pnlQLNVLayout);
        pnlQLNVLayout.setHorizontalGroup(
            pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrTableNhanVien)
            .addGroup(pnlQLNVLayout.createSequentialGroup()
                .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlQLNVLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlQLNVLayout.createSequentialGroup()
                                .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmail)
                                    .addComponent(lblSoDienThoai)
                                    .addComponent(lblDiaChi)
                                    .addComponent(lblMaNhanVien)
                                    .addComponent(lblTenNhanVien))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlQLNVLayout.createSequentialGroup()
                                        .addComponent(cmbTinhTP, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbQuanHuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbPhuongXa, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlQLNVLayout.createSequentialGroup()
                                        .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(pnlQLNVLayout.createSequentialGroup()
                                                .addGap(0, 186, Short.MAX_VALUE)
                                                .addComponent(lblTrinhDoNgoaiNgu)
                                                .addGap(31, 31, 31)
                                                .addComponent(cmbTrinhDoNgoaiNgu, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSoDienThoai, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTenNhanVien, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMaNhanVien, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(44, 44, 44)
                                        .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNgaySinh)
                                            .addComponent(lblGioiTinh)
                                            .addComponent(lblNgayVaoLam)
                                            .addComponent(lblVaiTro))
                                        .addGap(31, 31, 31)
                                        .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cmbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dtNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                            .addComponent(dtNgayVaoLam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(102, 102, 102))))
                            .addComponent(pnlChucNangTo, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlQLNVLayout.createSequentialGroup()
                                .addComponent(lblTrinhDoChuyenMon)
                                .addGap(50, 50, 50)
                                .addComponent(cmbTrinhDoChuyenMon, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(73, 73, 73)
                        .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAnhDaiDien, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQLNVLayout.createSequentialGroup()
                                .addComponent(btnChonHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)))
                        .addGap(184, 184, 184)))
                .addGap(68, 68, 68)
                .addComponent(btnHuongDan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        pnlQLNVLayout.setVerticalGroup(
            pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQLNVLayout.createSequentialGroup()
                .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuongDan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlQLNVLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlQLNVLayout.createSequentialGroup()
                                .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMaNhanVien)
                                    .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTenNhanVien))
                                .addGap(20, 20, 20)
                                .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSoDienThoai))
                                .addGap(18, 18, 18)
                                .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmail)))
                            .addGroup(pnlQLNVLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblGioiTinh)
                                    .addComponent(cmbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlQLNVLayout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(lblNgaySinh))
                                    .addGroup(pnlQLNVLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlQLNVLayout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(lblNgayVaoLam))
                                    .addGroup(pnlQLNVLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dtNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(16, 16, 16)
                                .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVaiTro)
                                    .addComponent(cmbVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblTrinhDoChuyenMon)
                                .addComponent(cmbTrinhDoChuyenMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblTrinhDoNgoaiNgu)
                                .addComponent(cmbTrinhDoNgoaiNgu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbTinhTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbQuanHuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDiaChi)
                            .addComponent(cmbPhuongXa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlChucNangTo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQLNVLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAnhDaiDien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChonHinhAnh)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrTableNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlQLNV, javax.swing.GroupLayout.DEFAULT_SIZE, 1637, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlQLNV, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonHinhAnh;
    private javax.swing.JButton btnHuongDan;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cmbGioiTinh;
    private javax.swing.JComboBox<String> cmbPhuongXa;
    private javax.swing.JComboBox<String> cmbQuanHuyen;
    private javax.swing.JComboBox<String> cmbTinhTP;
    private javax.swing.JComboBox<String> cmbTrinhDoChuyenMon;
    private javax.swing.JComboBox<String> cmbTrinhDoNgoaiNgu;
    private javax.swing.JComboBox<String> cmbVaiTro;
    private com.toedter.calendar.JDateChooser dtNgaySinh;
    private com.toedter.calendar.JDateChooser dtNgayVaoLam;
    private javax.swing.JLabel lblAnhDaiDien;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblMaNhanVien;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblNgayVaoLam;
    private javax.swing.JLabel lblSoDienThoai;
    private javax.swing.JLabel lblTenNhanVien;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JLabel lblTrinhDoChuyenMon;
    private javax.swing.JLabel lblTrinhDoNgoaiNgu;
    private javax.swing.JLabel lblVaiTro;
    private javax.swing.JPanel pnlChucNang;
    private javax.swing.JPanel pnlChucNangTo;
    private javax.swing.JPanel pnlQLNV;
    private javax.swing.JScrollPane scrTableNhanVien;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenNhanVien;
    // End of variables declaration//GEN-END:variables
}
