/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.border.MatteBorder;
import javax.swing.table.TableColumnModel;

import dao.BangChamCongNhanVienDAO;
import entity.BangChamCongNhanVien;
import entity.DiaChi;
import tablemodels.BangChamCongNVTableModel;
import dao.NhanVienDAO;
import tablemodels.NhanVienTableModel;
import entity.NhanVien;
import setting.PathSetting;

public class TimKiemChamCongNhanVien extends javax.swing.JPanel {

	/**
	 * Creates new form ChamCongNhanVien
	 */
	private BangChamCongNhanVienDAO chamCongNhanVienDAO;
	private BangChamCongNVTableModel chamCongNVTableModel;
	private List<BangChamCongNhanVien> dsCCNV;
	private NhanVienDAO nhanVienDAO;
	private NhanVienTableModel nhanVienTableModel;
	private List<NhanVien> dsNV;
	private static final String[] HEADERS = { "Mã chấm công", "Mã nhân viên", "Tên nhân viên", "Số giờ làm thêm",
			"Ngày chấm công", "Tình trạng", "Mã người chấm công", "Tên người chấm công", "Tình trạng công" };

	public TimKiemChamCongNhanVien() {
		chamCongNhanVienDAO = new BangChamCongNhanVienDAO();
		nhanVienDAO = new NhanVienDAO();
		initComponents();
		themSuKien();
		phimTatChoButton();
		setWidthTable();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void setWidthTable() {
		tblChamCong.getColumnModel().getColumn(0).setMinWidth(10);
		tblChamCong.getColumnModel().getColumn(1).setMinWidth(50);
		tblChamCong.getColumnModel().getColumn(2).setMinWidth(60);
		tblChamCong.getColumnModel().getColumn(3).setMinWidth(20);
		tblChamCong.getColumnModel().getColumn(4).setMinWidth(30);
		tblChamCong.getColumnModel().getColumn(5).setMinWidth(30);
		tblChamCong.getColumnModel().getColumn(6).setMinWidth(50);
		tblChamCong.getColumnModel().getColumn(7).setMinWidth(60);
		tblChamCong.getColumnModel().getColumn(8).setMinWidth(39);

	}
	private void phimTatChoButton() {
		btnTimKiem.setMnemonic('T');
        btnXoaRong.setMnemonic('X');
        rdTimKiem1.setMnemonic('1');
        rdTimKiem2.setMnemonic('2');
        rdTimKiem3.setMnemonic('3');
	}
	private void updateChamCongNhanVienModelTable(List<BangChamCongNhanVien> dsCCNV, String[] headers) {
		chamCongNVTableModel = new BangChamCongNVTableModel(dsCCNV, headers);
		tblChamCong.setModel(chamCongNVTableModel);
		setWidthTable();
		tblChamCong.updateUI();

	}

	private void fillThongTinChamCongNV(BangChamCongNhanVien chamCongNhanVien) {
		txtMaNhanVien.setText(chamCongNhanVien.getNhanVien().getMaNhanVien());
		txtTenNhanVien1.setText(chamCongNhanVien.getNhanVien().getTenNhanVien());
		// txtSoGioLamThemCC.setText(chamCongNhanVien.getNhanVien().getTenNhanVien());
		txtMaNguoiChamCong.setText(chamCongNhanVien.getNguoiChamCong().getMaNhanVien());
		txtTenNguoiChamCong.setText(chamCongNhanVien.getNguoiChamCong().getTenNhanVien());
		cmbTinhTrang.setSelectedItem(chamCongNhanVien.getTrangThai());
		// cmbCaLam.setSelectedItem(chamCongNhanVien.getCaLam());
		txtSoGioLamThem.setText(String.format("%.2f", chamCongNhanVien.getSoGioLamThem()));

		dtNgayChamCong.setDate(chamCongNhanVien.getNgayChamCong());
		cmbTinhTrangCong.setSelectedItem(chamCongNhanVien.getTinhTrangChamCong());
		//
	}

	private String maChamCongMoi(String maChamCong) {
		String maChamCongMoi = null;
		if (maChamCong == null) {
			maChamCongMoi = "CC000001";

		} else {
			int number = Integer.parseInt(maChamCong.substring(2));
			number++;
			maChamCongMoi = String.format("CC%06d", number);
			// System.out.println(maChamCongMoi);
		}

		return maChamCongMoi;
	}

	private void xoaRong() {
		txtMaNhanVien.setText("");
		txtTenNhanVien1.setText("");
		txtMaNguoiChamCong.setText("");
		dtNgayChamCong.setDate(null);
		dtNgayChamCong1.setDate(null);
		txtTenNguoiChamCong.setText("");
		txtSoGioLamThem.setText("");
		cmbTinhTrang.setSelectedItem("All");
		cmbTinhTrangCong.setSelectedItem("All");
	}

	private void themSuKien() {
		lblNgayChamCong1.setEnabled(false);
		dtNgayChamCong1.setDate(null);
		dsCCNV = chamCongNhanVienDAO.layDanhSachCCNV();
		dsNV = nhanVienDAO.layDanhSachNhanVien();
		updateChamCongNhanVienModelTable(dsCCNV, HEADERS);
		tblChamCong.addMouseListener(new MouseAdapter() {
			@SuppressWarnings("deprecation")
			@Override
			public void mouseClicked(MouseEvent e) {

				// TODO Auto-generated method stub
				String maChamCong = (String) tblChamCong.getModel().getValueAt(tblChamCong.getSelectedRow(), 0);
				// System.out.println(index);
				if (maChamCong != null) {
					BangChamCongNhanVien chamCongNhanVien = null;
					try {
						chamCongNhanVien = chamCongNhanVienDAO.timThongTinChamCongNhanVien(maChamCong);
						fillThongTinChamCongNV(chamCongNhanVien);

					} catch (Exception e2) {
						// TODO: handle exception
						e2.printStackTrace();
					}
				}
			}
		});

		// check radio button tìm kiếm 1 theo ngày tháng
		rdTimKiem1.addItemListener(new ItemListener() {

			@Override
			public void itemStateChanged(ItemEvent e) {
				if (e.getStateChange() == ItemEvent.SELECTED) {
					lblNgayChamCong1.setEnabled(false);

					dtNgayChamCong1.setEnabled(false);
					dtNgayChamCong1.setDate(null);
					System.out.println("Ngày");
				}

			}
		});
		// tim kiem theo tháng
		rdTimKiem2.addItemListener(new ItemListener() {

			@Override
			public void itemStateChanged(ItemEvent e) {
				if (e.getStateChange() == ItemEvent.SELECTED) {
					lblNgayChamCong1.setEnabled(false);
					dtNgayChamCong1.setEnabled(false);
					dtNgayChamCong1.setDate(null);
					System.out.println("Tháng");
				}

			}
		});
		// tìm kiếm theo khoảng thời gian
		rdTimKiem3.addItemListener(new ItemListener() {
			@Override
			public void itemStateChanged(ItemEvent e) {
				if (e.getStateChange() == ItemEvent.SELECTED) {
					lblNgayChamCong1.setEnabled(true);
					dtNgayChamCong1.setEnabled(true);
					for (Component c : dtNgayChamCong1.getComponents()) {
						c.setBackground(Color.WHITE);
					}

				}

			}
		});
		btnTimKiem.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				try {
					// TODO Auto-generated method stub
					btnTimKiemActionPerformed(e);
				} catch (Exception e2) {
					e2.printStackTrace();
				}

			}

			private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {
				// TODO Auto-generated method stub
				try {
					int kieuTimKiem = 1;
					if(rdTimKiem1.isSelected()) {
						kieuTimKiem = 1;
					}
					else if(rdTimKiem2.isSelected()) {
						kieuTimKiem = 2;
					}
					else if(rdTimKiem3.isSelected()) {
						kieuTimKiem = 3;
						
					}
					if(dtNgayChamCong1.getDate() == null && kieuTimKiem == 3) {
						JOptionPane.showMessageDialog(null, "Chưa chọn khoảng thời gian");
					}
					dsCCNV = layDanhSachChamCongTimKiem(kieuTimKiem);
//					System.out.println(dsCCNV);
					if (dsCCNV != null && dsCCNV.size() != 0) {
						System.out.println("AAAAAA");
						
						updateChamCongNhanVienModelTable(dsCCNV, HEADERS);
					} else
					{
						
						
						JOptionPane.showMessageDialog(null, "Không tìm thấy nhân viên nào");
						
					}
				} catch (Exception e2) {
					
					e2.printStackTrace();
				}

			}

			private List<BangChamCongNhanVien> layDanhSachChamCongTimKiem(int kieuTimKiem) {
				String maNV = txtMaNhanVien.getText().isEmpty() ? null : txtMaNhanVien.getText().trim();
				String tenNV = txtTenNhanVien1.getText().trim().isEmpty() ? null : txtTenNhanVien1.getText().trim();
				String maNguoiChamCong = txtMaNguoiChamCong.getText().isEmpty() ? null
						: txtMaNguoiChamCong.getText().trim();
				String tenNguoiChamCong = txtTenNguoiChamCong.getText().isEmpty() ? null
						: txtTenNguoiChamCong.getText().trim();
				Date ngayChamCong = null;
				Date denNgay = null;
				String soGioLamThem = txtSoGioLamThem.getText().isEmpty() ? null : txtSoGioLamThem.getText().trim();
				String tinhTrang = cmbTinhTrang.getSelectedItem().toString().trim().equalsIgnoreCase("All") ? null
						: cmbTinhTrang.getSelectedItem().toString().trim();
				String tinhTrangCong = cmbTinhTrangCong.getSelectedItem().toString().trim().equalsIgnoreCase("All")
						? null
						: cmbTinhTrangCong.getSelectedItem().toString().trim();
				try {
					ngayChamCong = dtNgayChamCong.getDate();
					denNgay = dtNgayChamCong1.getDate();

				} catch (Exception e) {
					e.printStackTrace();
					
				}
				try {
					return chamCongNhanVienDAO.timKiemChamCongNhieuThuocTinh(maNV, tenNV, ngayChamCong,denNgay, soGioLamThem,
							tinhTrang, maNguoiChamCong, tenNguoiChamCong, tinhTrangCong, kieuTimKiem);
				} catch (Exception e) {
					
					e.printStackTrace();
				}
				return null;

			};

		});

		btnXoaRong.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				btnXoaRongActionPerformed(e);

			}

			private void btnXoaRongActionPerformed(ActionEvent evt) {
				xoaRong();

			}

		});

	}

	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupTimKiem = new javax.swing.ButtonGroup();
        scrChamCong = new javax.swing.JScrollPane();
        tblChamCong = new javax.swing.JTable();
        lblNgayChamCong = new javax.swing.JLabel();
        lblTinhTrang = new javax.swing.JLabel();
        lblTenNhanVien = new javax.swing.JLabel();
        lblMaNhanVien = new javax.swing.JLabel();
        txtMaNhanVien = new javax.swing.JTextField();
        lblMaNguoiChamCong = new javax.swing.JLabel();
        txtMaNguoiChamCong = new javax.swing.JTextField();
        dtNgayChamCong = new com.toedter.calendar.JDateChooser();
        cmbTinhTrang = new javax.swing.JComboBox<>();
        lblMaNguoiChamCong1 = new javax.swing.JLabel();
        txtTenNguoiChamCong = new javax.swing.JTextField();
        txtTenNhanVien1 = new javax.swing.JTextField();
        lblSoGioLamThem = new javax.swing.JLabel();
        txtSoGioLamThem = new javax.swing.JTextField();
        lblTinhTrangCong = new javax.swing.JLabel();
        cmbTinhTrangCong = new javax.swing.JComboBox<>();
        btnTimKiem = new javax.swing.JButton();
        btnXoaRong = new javax.swing.JButton();
        dtNgayChamCong1 = new com.toedter.calendar.JDateChooser();
        lblNgayChamCong1 = new javax.swing.JLabel();
        lblKieuTimKiem = new javax.swing.JLabel();
        rdTimKiem1 = new javax.swing.JRadioButton();
        rdTimKiem2 = new javax.swing.JRadioButton();
        rdTimKiem3 = new javax.swing.JRadioButton();
        lblChiTietKieuTimKiem = new javax.swing.JLabel();
        lblChiTietKieuTimKiem1 = new javax.swing.JLabel();
        lblChiTietKieuTimKiem2 = new javax.swing.JLabel();
        lblChiTietKieuTimKiem3 = new javax.swing.JLabel();
        lblChiTietKieuTimKiem4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrChamCong.setBackground(new java.awt.Color(255, 255, 255));
        scrChamCong.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bảng chấm công", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16))); // NOI18N

        tblChamCong.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tblChamCong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã chấm công", "Mã nhân viên", "Họ và tên", "Ngày chấm công", "Ca làm", "Tình trạng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblChamCong.setMinimumSize(null);
        tblChamCong.setSelectionBackground(new java.awt.Color(51, 153, 255));
        scrChamCong.setViewportView(tblChamCong);

        add(scrChamCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 1660, 450));

        lblNgayChamCong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNgayChamCong.setText("Ngày chấm công:");
        add(lblNgayChamCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 40));

        lblTinhTrang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTinhTrang.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTinhTrang.setText("Tình trạng:");
        add(lblTinhTrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 40));

        lblTenNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTenNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTenNhanVien.setText("Tên nhân viên:");
        add(lblTenNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 40));

        lblMaNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMaNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMaNhanVien.setText("Mã nhân viên:");
        add(lblMaNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 113, 40));

        txtMaNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMaNhanVien.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));
        add(txtMaNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 220, 34));

        lblMaNguoiChamCong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMaNguoiChamCong.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMaNguoiChamCong.setText("Mã người chấm công:");
        add(lblMaNguoiChamCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, 30));

        txtMaNguoiChamCong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMaNguoiChamCong.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));
        add(txtMaNguoiChamCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 220, 34));

        dtNgayChamCong.setBackground(new java.awt.Color(255, 255, 255));
        dtNgayChamCong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(dtNgayChamCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 220, 40));

        cmbTinhTrang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbTinhTrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Đi đúng giờ", "Đi trễ", "Nghỉ có phép" }));
        cmbTinhTrang.setToolTipText("");
        add(cmbTinhTrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 220, 40));

        lblMaNguoiChamCong1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMaNguoiChamCong1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMaNguoiChamCong1.setText("Tên người chấm công:");
        add(lblMaNguoiChamCong1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, 30));

        txtTenNguoiChamCong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTenNguoiChamCong.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));
        add(txtTenNguoiChamCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 220, 34));

        txtTenNhanVien1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTenNhanVien1.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));
        add(txtTenNhanVien1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 220, 34));

        lblSoGioLamThem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSoGioLamThem.setText("Số giờ làm thêm:");
        add(lblSoGioLamThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, 30));

        txtSoGioLamThem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSoGioLamThem.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));
        add(txtSoGioLamThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 100, 34));

        lblTinhTrangCong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTinhTrangCong.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTinhTrangCong.setText("Tình trạng Công:");
        add(lblTinhTrangCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, -1, 40));

        cmbTinhTrangCong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbTinhTrangCong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Nữa công", "Đủ công" }));
        add(cmbTinhTrangCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 220, 40));

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        btnTimKiem.setMnemonic('T');
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(btnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 190, 39));

        btnXoaRong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXoaRong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/eraser.png"))); // NOI18N
        btnXoaRong.setMnemonic('X');
        btnXoaRong.setText("Xóa rỗng");
        btnXoaRong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnXoaRong.setPreferredSize(new java.awt.Dimension(137, 33));
        add(btnXoaRong, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 192, 39));

        dtNgayChamCong1.setBackground(new java.awt.Color(255, 255, 255));
        dtNgayChamCong1.setEnabled(false);
        dtNgayChamCong1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(dtNgayChamCong1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 220, 40));

        lblNgayChamCong1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNgayChamCong1.setText("Đến ngày:");
        add(lblNgayChamCong1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, 40));

        lblKieuTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblKieuTimKiem.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblKieuTimKiem.setText("Kiểu tìm kiếm");
        add(lblKieuTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 330, -1, 40));

        groupTimKiem.add(rdTimKiem1);
        rdTimKiem1.setSelected(true);
        rdTimKiem1.setText("(1)");
        add(rdTimKiem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 340, -1, -1));

        groupTimKiem.add(rdTimKiem2);
        rdTimKiem2.setText("(2)");
        add(rdTimKiem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 340, -1, -1));

        groupTimKiem.add(rdTimKiem3);
        rdTimKiem3.setText("(3)");
        add(rdTimKiem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 340, -1, -1));

        lblChiTietKieuTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblChiTietKieuTimKiem.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblChiTietKieuTimKiem.setText("Chú thích (?)");
        add(lblChiTietKieuTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 200, -1, 40));

        lblChiTietKieuTimKiem1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblChiTietKieuTimKiem1.setText("(1) Tìm kiếm theo ngày");
        add(lblChiTietKieuTimKiem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 240, -1, 40));

        lblChiTietKieuTimKiem2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblChiTietKieuTimKiem2.setText("(2) Tìm kiếm theo tháng");
        add(lblChiTietKieuTimKiem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 280, -1, 40));

        lblChiTietKieuTimKiem3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblChiTietKieuTimKiem3.setText("(3) Tìm kiếm theo khoảng thời gian");
        add(lblChiTietKieuTimKiem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 320, -1, 40));

        lblChiTietKieuTimKiem4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblChiTietKieuTimKiem4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblChiTietKieuTimKiem4.setText("Hướng dẫn sử dụng");
        add(lblChiTietKieuTimKiem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
		////////

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoaRong;
    private javax.swing.JComboBox<String> cmbTinhTrang;
    private javax.swing.JComboBox<String> cmbTinhTrangCong;
    private com.toedter.calendar.JDateChooser dtNgayChamCong;
    private com.toedter.calendar.JDateChooser dtNgayChamCong1;
    private javax.swing.ButtonGroup groupTimKiem;
    private javax.swing.JLabel lblChiTietKieuTimKiem;
    private javax.swing.JLabel lblChiTietKieuTimKiem1;
    private javax.swing.JLabel lblChiTietKieuTimKiem2;
    private javax.swing.JLabel lblChiTietKieuTimKiem3;
    private javax.swing.JLabel lblChiTietKieuTimKiem4;
    private javax.swing.JLabel lblKieuTimKiem;
    private javax.swing.JLabel lblMaNguoiChamCong;
    private javax.swing.JLabel lblMaNguoiChamCong1;
    private javax.swing.JLabel lblMaNhanVien;
    private javax.swing.JLabel lblNgayChamCong;
    private javax.swing.JLabel lblNgayChamCong1;
    private javax.swing.JLabel lblSoGioLamThem;
    private javax.swing.JLabel lblTenNhanVien;
    private javax.swing.JLabel lblTinhTrang;
    private javax.swing.JLabel lblTinhTrangCong;
    private javax.swing.JRadioButton rdTimKiem1;
    private javax.swing.JRadioButton rdTimKiem2;
    private javax.swing.JRadioButton rdTimKiem3;
    private javax.swing.JScrollPane scrChamCong;
    private javax.swing.JTable tblChamCong;
    private javax.swing.JTextField txtMaNguoiChamCong;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtSoGioLamThem;
    private javax.swing.JTextField txtTenNguoiChamCong;
    private javax.swing.JTextField txtTenNhanVien1;
    // End of variables declaration//GEN-END:variables
}
